-- TGG relational schema proposal (MVP subset)
CREATE TABLE IF NOT EXISTS instruments (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(32) UNIQUE NOT NULL,
  asset_class VARCHAR(32) NOT NULL,
  name VARCHAR(128) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ohlcv (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(32) NOT NULL,
  ts TIMESTAMP NOT NULL,
  open DOUBLE PRECISION NOT NULL,
  high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL,
  close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL,
  source VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS signals (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(32) NOT NULL,
  signal_type VARCHAR(64) NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  explanation TEXT NOT NULL,
  provenance TEXT NOT NULL,
  risk_summary TEXT NOT NULL,
  feature_snapshot TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS paper_trades (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(32) NOT NULL,
  side VARCHAR(8) NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  entry_price DOUBLE PRECISION NOT NULL,
  stop_loss DOUBLE PRECISION NOT NULL,
  take_profit DOUBLE PRECISION NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  pnl DOUBLE PRECISION NOT NULL DEFAULT 0,
  signal_snapshot TEXT NOT NULL DEFAULT '',
  open_reason TEXT NOT NULL DEFAULT '',
  opened_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id SERIAL PRIMARY KEY,
  action VARCHAR(128) NOT NULL,
  actor VARCHAR(64) NOT NULL DEFAULT 'system',
  payload TEXT NOT NULL,
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
